import { EXRExporter } from "three/examples/jsm/Addons.js";

export const NavLinks = [
    {
      id: "About",
      title: "About",
    },
    {
      id: "Know-how",
      title: "Know-how",
    },
    {
        id: "Recruitment",
        title: "Recruitment",
      },
    {
      id: "Contact",
      title: "Contact",
    },
  ];

  export const RecruitmentDashboardLinks = [
    {
      id: "RecruitmentEdit",
      title: "Edit Recruitment",
    },
    {
      id: "ManageApplicants",
      title: "Manage Applicants",
    },
    {
      id: "ApplicantsOfferRanking",
      title: "Applicants Offer Ranking",
    },
    {
      id: "Meetings",
      title: "Meetings",
    },
    {
      id: "YourOwnScore",
      title: "Your Own Score",
    },
    {
      id: "FinalRanking",
      title: "Final Ranking",
    },
    {
      id: "FinishRecruitment",
      title: "Finish Recruitment",
    },
    {
      id: "DeleteRecruitment",
      title: "Delete Recruitment",
    },
  ];

  export const existingLanguages = [
    "afrikaans",
    "albanian",
    "amharic",
    "arabic",
    "armenian",
    "basque",
    "bengali",
    "bosnian",
    "bulgarian",
    "catalan",
    "chinese",
    "croatian",
    "czech",
    "danish",
    "dutch",
    "english",
    "estonian",
    "finnish",
    "french",
    "georgian",
    "german",
    "greek",
    "gujarati",
    "haitian creole",
    "hebrew",
    "hindi",
    "hungarian",
    "icelandic",
    "indonesian",
    "irish",
    "italian",
    "japanese",
    "kannada",
    "kazakh",
    "korean",
    "kurdish",
    "latvian",
    "lithuanian",
    "macedonian",
    "malay",
    "maltese",
    "mandarin",
    "marathi",
    "nepali",
    "norwegian",
    "pashto",
    "persian",
    "polish",
    "portuguese",
    "punjabi",
    "romanian",
    "russian",
    "serbian",
    "sinhala",
    "slovak",
    "slovenian",
    "spanish",
    "swahili",
    "swedish",
    "tamil",
    "telugu",
    "thai",
    "turkish",
    "ukrainian",
    "urdu",
    "uzbek",
    "vietnamese",
    "welsh",
    "yiddish",
    "yoruba",
  ];
  